package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deposit generated by hbm2java
 */
@Entity
@Table(name = "deposit", catalog = "pi_otdav")
public class Deposit implements java.io.Serializable {

	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idDeposit;
	@ManyToOne
	@JoinColumn(name = "idUser", nullable = false)
	private User user;
	@ManyToOne
	@JoinColumn(name = "idWorkDeposit", nullable = false)
	private WorkDeposit workDeposit;
	private Integer numDepot;
	private Date dateDepot;
	private Integer numQuitance;
	private Date dateDebutDepot;
	private Date dateFinDepot;
	private String etat;
	@ManyToOne
	@JoinColumn(name = "categoryDeposit", nullable = false)
	private CategoryDeposit categoryDeposit;

	public Deposit() {
	}

	public Deposit(int idDeposit, User user, WorkDeposit workDeposit) {
		this.idDeposit = idDeposit;
		this.user = user;
		this.workDeposit = workDeposit;
	}

	public Deposit(int idDeposit, User user, WorkDeposit workDeposit, Integer numDepot, Date dateDepot,
			Integer numQuitance, Date dateDebutDepot, Date dateFinDepot, String etat) {
		this.idDeposit = idDeposit;
		this.user = user;
		this.workDeposit = workDeposit;
		this.numDepot = numDepot;
		this.dateDepot = dateDepot;
		this.numQuitance = numQuitance;
		this.dateDebutDepot = dateDebutDepot;
		this.dateFinDepot = dateFinDepot;
		this.etat = etat;
	}
	
	
	
	public Deposit(int idDeposit,Date dateDebutDepot, Date dateFinDepot) {
		this.idDeposit = idDeposit;
		this.dateDebutDepot = dateDebutDepot;
		this.dateFinDepot = dateFinDepot;
		
	}
	
	
	public Deposit(int idDeposit, WorkDeposit workDeposit,CategoryDeposit categoryDeposit ) {
		this.idDeposit = idDeposit;
		
		this.workDeposit = workDeposit;
		this.categoryDeposit= categoryDeposit;
		
	}

	
	@Column(name = "idDeposit", unique = true, nullable = false)
	public int getIdDeposit() {
		return this.idDeposit;
	}

	public void setIdDeposit(int idDeposit) {
		this.idDeposit = idDeposit;
	}

	
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	
	public WorkDeposit getWorkDeposit() {
		return this.workDeposit;
	}

	public void setWorkDeposit(WorkDeposit workDeposit) {
		this.workDeposit = workDeposit;
	}

	@Column(name = "numDepot")
	public Integer getNumDepot() {
		return this.numDepot;
	}

	public void setNumDepot(Integer numDepot) {
		this.numDepot = numDepot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDepot", length = 19)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Column(name = "numQuitance")
	public Integer getNumQuitance() {
		return this.numQuitance;
	}

	public void setNumQuitance(Integer numQuitance) {
		this.numQuitance = numQuitance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDebutDepot", length = 19)
	public Date getDateDebutDepot() {
		return this.dateDebutDepot;
	}

	public void setDateDebutDepot(Date dateDebutDepot) {
		this.dateDebutDepot = dateDebutDepot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateFinDepot", length = 19)
	public Date getDateFinDepot() {
		return this.dateFinDepot;
	}

	public void setDateFinDepot(Date dateFinDepot) {
		this.dateFinDepot = dateFinDepot;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}
	public CategoryDeposit getCategoryDep() {
		return this.categoryDeposit;
	}
	
	public void setCategoryDep(CategoryDeposit categoryDeposit) {
		this.categoryDeposit = categoryDeposit;
	}
}
