package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "pi_otdav")
public class Division implements java.io.Serializable {

	private int idDivision;
	private User user;
	private Work work;

	public Division() {
	}

	public Division(int idDivision, User user, Work work) {
		this.idDivision = idDivision;
		this.user = user;
		this.work = work;
	}

	@Id

	@Column(name = "idDivision", unique = true, nullable = false)
	public int getIdDivision() {
		return this.idDivision;
	}

	public void setIdDivision(int idDivision) {
		this.idDivision = idDivision;
	}

	@ManyToOne
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "idWork", nullable = false)
	public Work getWork() {
		return this.work;
	}

	public void setWork(Work work) {
		this.work = work;
	}

}
