package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", catalog = "pi_otdav")
public class Document implements java.io.Serializable {
	
	@Id	
	@GeneratedValue (strategy = GenerationType.AUTO )
	@Column(name = "idDocument", unique = true, nullable = false)
	private int idDocument;
	@ManyToOne
	@JoinColumn(name = "user", nullable = false)
	private User user;


	private Date dateAjout;
	private String lieu;
	private String nomDocument;
	private Integer typeDocument;

	public Document() {
	}
	public Document(int idDocument) {
		this.idDocument = idDocument;
	}

	public Document(int idDocument, Date dateAjout, String lieu, String nomDocument, Integer typeDocument) {
		this.idDocument = idDocument;
		this.dateAjout = dateAjout;
		this.lieu = lieu;
		this.nomDocument = nomDocument;
		this.typeDocument = typeDocument;
	}
	public Document( Date dateAjout, String lieu, String nomDocument, Integer typeDocument) {		
		this.dateAjout = dateAjout;
		this.lieu = lieu;
		this.nomDocument = nomDocument;
		this.typeDocument = typeDocument;
	}
	public Document(int idDocument, User user) {
		this.idDocument = idDocument;
		this.user = user;
	}

	public Document(int idDocument, User user, Date dateAjout, String lieu, String nomDocument, Integer typeDocument) {
		this.idDocument = idDocument;
		this.user = user;
		this.dateAjout = dateAjout;
		this.lieu = lieu;
		this.nomDocument = nomDocument;
		this.typeDocument = typeDocument;
	}


	public int getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(int idDocument) {
		this.idDocument = idDocument;
	}

	
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateAjout", length = 19)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@Column(name = "lieu", length = 254)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@Column(name = "nomDocument", length = 254)
	public String getNomDocument() {
		return this.nomDocument;
	}

	public void setNomDocument(String nomDocument) {
		this.nomDocument = nomDocument;
	}

	@Column(name = "typeDocument")
	public Integer getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(Integer typeDocument) {
		this.typeDocument = typeDocument;
	}

}
