package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fees generated by hbm2java
 */
@Entity
@Table(name = "fees", catalog = "pi_otdav")
public class Fees implements java.io.Serializable {
	@Id
	private int idFees;
	private Float montant;
	@ManyToOne
	@JoinColumn(name = "categoryUser", nullable = false)
	private CategoryUser categoryUser;
	@ManyToOne
	@JoinColumn(name = "user", nullable = false)
	private User user;
	public Fees() {
	}

	public Fees(int idFees, Float montant, CategoryUser categoryUser, User user) {
		super();
		this.idFees = idFees;
		this.montant = montant;
		this.categoryUser = categoryUser;
		this.user = user;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public void setCategoryUser(CategoryUser categoryUser) {
		this.categoryUser = categoryUser;
	}

	public Fees(int idFees, Float montant, int idCategory) {
		super();
		this.idFees = idFees;
		this.montant = montant;
		this.categoryUser = categoryUser;
	}

	public CategoryUser getCategoryUser() {
		return categoryUser;
	}

	public void setCategoryUser(int idCategory) {
		this.categoryUser = categoryUser;
	}

	public Fees(int idFees, Float montant) {
		this.idFees = idFees;
		this.montant = montant;
	}


	@Column(name = "idFees", unique = true, nullable = false)
	public int getIdFees() {
		return this.idFees;
	}

	public void setIdFees(int idFees) {
		this.idFees = idFees;
	}


	@Column(name = "montant", precision = 12, scale = 0)
	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

}
