package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resignation generated by hbm2java
 */
@Entity
@Table(name = "resignation", catalog = "pi_otdav")
public class Resignation implements java.io.Serializable {
	@Id
	private int idResignation;
	@ManyToOne
	@JoinColumn(name = "user", nullable = false)
	private User user;
	public Resignation() {
	}

	public Resignation(int idResignation, User user) {
		this.idResignation = idResignation;
		this.user = user;
	}


	
	@Column(name = "idResignation", unique = true, nullable = false)
	public int getIdResignation() {
		return this.idResignation;
	}

	public void setIdResignation(int idResignation) {
		this.idResignation = idResignation;
	}

	
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
