package piotdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "pi_otdav")
public class User implements java.io.Serializable {
	@Id
	@Column(name = "idUser", unique = true, nullable = false)
	private int idUser;
	@ManyToOne
	private Resignation resignation;
	
	private String lastName;
	private String firstName;
	private String cin;
	private Date dateDelivrance;
	private String adresse;
	private String ville;
	private String codePostal;
	private String civilite;
	private String email;
	private Date dateNaissance;
	private Integer identifiantUnique;
	private String lieuNaissance;
	private String nationalite;
	private String raisonSocial;
	private Integer numChild;
	private Integer numEnregistrements;
	private String photo;
	private String fax;
	private String tel;
	private String rib;
	private String sexe;
	private Date etatcivil;
	private Date dateEnregistrement;
	private Integer typeEnregistrement;
	private Integer typePerson;
	private String login;
	private String password;
	private Integer role;
	private Integer state;
	@OneToMany(mappedBy = "user")
	private Set<Deposit> deposits;
	@OneToMany(mappedBy = "user")
	private Set<Notification> notifications ;
	@OneToMany(mappedBy = "user")
	private Set<Work> works ;
	@OneToMany(mappedBy = "user")
	private Set<Division> divisions ;
	@OneToMany(mappedBy = "user")
	private Set<Document> documents ;
	@OneToMany(mappedBy = "user")
	private Set<Resignation> resignations;
	

	public User() {
	}

	public User(int idUser) {
		this.idUser = idUser;
	}

	public User(int idUser, Resignation resignation, String lastName, String firstName, String cin, Date dateDelivrance,
			String adresse, String ville, String codePostal, String civilite, String email, Date dateNaissance,
			Integer identifiantUnique, String lieuNaissance, String nationalite, String raisonSocial, Integer numChild,
			Integer numEnregistrements, String photo, String fax, String tel, String rib, String sexe, Date etatcivil,
			Date dateEnregistrement, Integer typeEnregistrement, Integer typePerson, String login, String password,
			Integer role, Integer state) {
		this.idUser = idUser;
		this.resignation = resignation;
		this.lastName = lastName;
		this.firstName = firstName;
		this.cin = cin;
		this.dateDelivrance = dateDelivrance;
		this.adresse = adresse;
		this.ville = ville;
		this.codePostal = codePostal;
		this.civilite = civilite;
		this.email = email;
		this.dateNaissance = dateNaissance;
		this.identifiantUnique = identifiantUnique;
		this.lieuNaissance = lieuNaissance;
		this.nationalite = nationalite;
		this.raisonSocial = raisonSocial;
		this.numChild = numChild;
		this.numEnregistrements = numEnregistrements;
		this.photo = photo;
		this.fax = fax;
		this.tel = tel;
		this.rib = rib;
		this.sexe = sexe;
		this.etatcivil = etatcivil;
		this.dateEnregistrement = dateEnregistrement;
		this.typeEnregistrement = typeEnregistrement;
		this.typePerson = typePerson;
		this.login = login;
		this.password = password;
		this.role = role;
		this.state = state;
	}

	
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	
	public Resignation getResignation() {
		return this.resignation;
	}

	public void setResignation(Resignation resignation) {
		this.resignation = resignation;
	}

	@Column(name = "lastName", length = 254)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "firstName", length = 254)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "cin", length = 254)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDelivrance", length = 19)
	public Date getDateDelivrance() {
		return this.dateDelivrance;
	}

	public void setDateDelivrance(Date dateDelivrance) {
		this.dateDelivrance = dateDelivrance;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "ville", length = 254)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "codePostal", length = 254)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "civilite", length = 254)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateNaissance", length = 19)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "identifiant_unique_")
	public Integer getIdentifiantUnique() {
		return this.identifiantUnique;
	}

	public void setIdentifiantUnique(Integer identifiantUnique) {
		this.identifiantUnique = identifiantUnique;
	}

	@Column(name = "lieuNaissance", length = 254)
	public String getLieuNaissance() {
		return this.lieuNaissance;
	}

	public void setLieuNaissance(String lieuNaissance) {
		this.lieuNaissance = lieuNaissance;
	}

	@Column(name = "nationalite", length = 254)
	public String getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(String nationalite) {
		this.nationalite = nationalite;
	}

	@Column(name = "raisonSocial", length = 254)
	public String getRaisonSocial() {
		return this.raisonSocial;
	}

	public void setRaisonSocial(String raisonSocial) {
		this.raisonSocial = raisonSocial;
	}

	@Column(name = "numChild")
	public Integer getNumChild() {
		return this.numChild;
	}

	public void setNumChild(Integer numChild) {
		this.numChild = numChild;
	}

	@Column(name = "numEnregistrements")
	public Integer getNumEnregistrements() {
		return this.numEnregistrements;
	}

	public void setNumEnregistrements(Integer numEnregistrements) {
		this.numEnregistrements = numEnregistrements;
	}

	@Column(name = "photo", length = 254)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "fax", length = 254)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "tel", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "rib", length = 254)
	public String getRib() {
		return this.rib;
	}

	public void setRib(String rib) {
		this.rib = rib;
	}

	@Column(name = "sexe", length = 1)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "etatcivil", length = 19)
	public Date getEtatcivil() {
		return this.etatcivil;
	}

	public void setEtatcivil(Date etatcivil) {
		this.etatcivil = etatcivil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEnregistrement", length = 19)
	public Date getDateEnregistrement() {
		return this.dateEnregistrement;
	}

	public void setDateEnregistrement(Date dateEnregistrement) {
		this.dateEnregistrement = dateEnregistrement;
	}

	@Column(name = "typeEnregistrement")
	public Integer getTypeEnregistrement() {
		return this.typeEnregistrement;
	}

	public void setTypeEnregistrement(Integer typeEnregistrement) {
		this.typeEnregistrement = typeEnregistrement;
	}

	@Column(name = "typePerson")
	public Integer getTypePerson() {
		return this.typePerson;
	}

	public void setTypePerson(Integer typePerson) {
		this.typePerson = typePerson;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role")
	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	
	public Set<Deposit> getDeposits() {
		return this.deposits;
	}

	public void setDeposits(Set<Deposit> deposits) {
		this.deposits = deposits;
	}

	
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	
	public Set<Work> getWorks() {
		return this.works;
	}

	public void setWorks(Set<Work> works) {
		this.works = works;
	}

	
	public Set<Division> getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Set<Division> divisions) {
		this.divisions = divisions;
	}

	
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	
	public Set<Resignation> getResignations() {
		return this.resignations;
	}

	public void setResignations(Set<Resignation> resignations) {
		this.resignations = resignations;
	}

}
